version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.6

workflows:
  imagickbuild:
    jobs:
      - docker-rpmbuild/rpmbuild:
          package-vcs-url: https://github.com/aursu/rpmbuild-imagick
          name: centos7imagickbuild
          base_service: centos7imagickbase
          build_service: centos7imagickbuild
          bintray_uploader: centos7bintray
          bintray-repo: custom
